export { default as Complete } from './Complete.vue'
export { default as Download } from './Download.vue'
export { default as History } from './History.vue'
export { default as Home } from './Home.vue'
export { default as Auth } from './Auth.vue'
export { default as Profile } from './Profile.vue'
export { default as Upload } from './Upload.vue'
